INSERT INTO TEACHER(NAME , SURNAME , AGE , DEGREE , TEACH_LESSON , ACTIVE) VALUES ('Akif' , 'Samirov' , 54 , 'Muellim' , 'Kimya' , 1);

INSERT INTO TEACHER(NAME , SURNAME , AGE , DEGREE , TEACH_LESSON , ACTIVE) VALUES ('Firuze' , 'Samirova' , 45 , 'Dosent' , 'Cografiya' , 1);


INSERT INTO TEACHER(NAME , SURNAME , AGE , DEGREE , TEACH_LESSON , ACTIVE) VALUES ('Lale' , 'Qenberova' , 33 , 'Tecrubeci' , 'English' , 1);

INSERT INTO TEACHER(NAME , SURNAME , AGE , DEGREE , TEACH_LESSON , ACTIVE) VALUES ('Zeyneb' ,'Gulsadova' , 23 , 'Dosent' , 'Riyaziyyat',1);


INSERT INTO TEACHER(NAME , SURNAME , AGE , DEGREE , TEACH_LESSON , ACTIVE) VALUES ('Nadir' , 'Dagli' , 36 , 'Doktor' , 'Bilogiya' , 1);

INSERT INTO TEACHER(NAME , SURNAME , AGE , DEGREE , TEACH_LESSON , ACTIVE) VALUES ('Vuqar' , 'Nubarov' , 40 , 'Professor' , 'Fizika' , 1);


INSERT INTO STUDENT(NAME , SURNAME , AGE , COURSE, GROUP_NUMBER, ACTIVE , TEACHER_ID) 
VALUES ('Malik' , 'Demirov' , 23 , 2 , 684.1 , 1 , 1);

INSERT INTO STUDENT(NAME , SURNAME , AGE , COURSE, GROUP_NUMBER, ACTIVE , TEACHER_ID) 
VALUES ('Qasim' , 'Demirov' , 23 , 2 , 684.1 , 1 , 1);


INSERT INTO STUDENT(NAME , SURNAME , AGE , COURSE, GROUP_NUMBER, ACTIVE , TEACHER_ID) 
VALUES ('Cabbar' , 'Demirov' , 23 , 2 , 684.1 , 1 , 1);


INSERT INTO STUDENT(NAME , SURNAME , AGE , COURSE, GROUP_NUMBER, ACTIVE , TEACHER_ID) 
VALUES ('Eli' , 'Demirov' , 23 , 2 , 684.1 , 1 , 2);


INSERT INTO STUDENT(NAME , SURNAME , AGE , COURSE, GROUP_NUMBER, ACTIVE , TEACHER_ID) 
VALUES ('Babek' , 'Demirov' , 23 , 2 , 684.1 , 1 , 2);


INSERT INTO STUDENT(NAME , SURNAME , AGE , COURSE, GROUP_NUMBER, ACTIVE , TEACHER_ID) 
VALUES ('Malik' , 'Demirov' , 23 , 2 , 684.1 , 1 , 1);

INSERT INTO STUDENT(NAME , SURNAME , AGE , COURSE, GROUP_NUMBER, ACTIVE , TEACHER_ID) 
VALUES ('Qasim' , 'Demirov' , 23 , 2 , 684.1 , 1 , 3);


INSERT INTO STUDENT(NAME , SURNAME , AGE , COURSE, GROUP_NUMBER, ACTIVE , TEACHER_ID) 
VALUES ('Cabbar' , 'Demirov' , 23 , 2 , 684.1 , 1 , 5);


INSERT INTO STUDENT(NAME , SURNAME , AGE , COURSE, GROUP_NUMBER, ACTIVE , TEACHER_ID) 
VALUES ('Eli' , 'Demirov' , 23 , 2 , 684.1 , 1 , 6);


INSERT INTO STUDENT(NAME , SURNAME , AGE , COURSE, GROUP_NUMBER, ACTIVE , TEACHER_ID) 
VALUES ('Babek' , 'Demirov' , 23 , 2 , 684.1 , 1 , 4);



INSERT INTO STUDENT(NAME , SURNAME , AGE , COURSE, GROUP_NUMBER, ACTIVE , TEACHER_ID) 
VALUES ('Qasim' , 'Demirov' , 23 , 2 , 684.1 , 1 , 2);


INSERT INTO STUDENT(NAME , SURNAME , AGE , COURSE, GROUP_NUMBER, ACTIVE , TEACHER_ID) 
VALUES ('Cabbar' , 'Demirov' , 23 , 2 , 684.1 , 1 , 1);


INSERT INTO STUDENT(NAME , SURNAME , AGE , COURSE, GROUP_NUMBER, ACTIVE , TEACHER_ID) 
VALUES ('Eli' , 'Demirov' , 23 , 2 , 684.1 , 1 , 4);


INSERT INTO STUDENT(NAME , SURNAME , AGE , COURSE, GROUP_NUMBER, ACTIVE , TEACHER_ID) 
VALUES ('Babek' , 'Demirov' , 23 , 2 , 684.1 , 1 , 5);