INSERT INTO TEACHER(NAME , SURNAME , AGE , DEGREE , TEACH_LESSON , ACTIVE) VALUES ('Akif' , 'Samirov' , 23 , 'Ali Savadli' , 'Riyaziyyat' , 1);

INSERT INTO TEACHER(NAME , SURNAME , AGE , DEGREE , TEACH_LESSON , ACTIVE) VALUES ('Asim' , 'Samirov' , 23 , 'Ali Savadli' , 'Riyaziyyat' , 1);


INSERT INTO STUDENT(NAME , SURNAME , AGE , COURSE, GROUP_NUMBER, ACTIVE , TEACHER_ID) 
VALUES ('Malik' , 'Demirov' , 23 , 2 , 684.1 , 1 , 1);

INSERT INTO STUDENT(NAME , SURNAME , AGE , COURSE, GROUP_NUMBER, ACTIVE , TEACHER_ID) 
VALUES ('Qasim' , 'Demirov' , 23 , 2 , 684.1 , 1 , 1);


INSERT INTO STUDENT(NAME , SURNAME , AGE , COURSE, GROUP_NUMBER, ACTIVE , TEACHER_ID) 
VALUES ('Cabbar' , 'Demirov' , 23 , 2 , 684.1 , 1 , 1);


INSERT INTO STUDENT(NAME , SURNAME , AGE , COURSE, GROUP_NUMBER, ACTIVE , TEACHER_ID) 
VALUES ('Eli' , 'Demirov' , 23 , 2 , 684.1 , 1 , 2);


INSERT INTO STUDENT(NAME , SURNAME , AGE , COURSE, GROUP_NUMBER, ACTIVE , TEACHER_ID) 
VALUES ('Babek' , 'Demirov' , 23 , 2 , 684.1 , 1 , 2);